import type { Invitation, InvitationStats, Media, Vendor } from '@/types';

export const MOCK_VENDORS: Vendor[] = [
  {
    id: 'v1',
    type: 'PHOTOGRAPHER',
    state: 'ACTIVE',
    name: 'Rhythm & Light Co.',
    contactNumber: '+91 98200 11122',
    email: 'hello@rhythmlight.in',
    documents: { aadhar: 'XXXX-XXXX-1234' },
    providesDroneShoot: true,
    providesVideography: true,
  },
  {
    id: 'v2',
    type: 'CATERER',
    state: 'ACTIVE',
    name: 'Culinary Canvas',
    contactNumber: '+91 91234 56789',
    email: 'orders@culinarycanvas.in',
    documents: { aadhar: 'XXXX-XXXX-5678' },
    cuisines: ['North Indian', 'Italian', 'Continental'],
    providesCutlery: true,
  },
  {
    id: 'v3',
    type: 'VENUE',
    state: 'ACTIVE',
    name: 'The Marigold Estate',
    contactNumber: '+91 99887 11122',
    email: 'bookings@marigoldestate.in',
    documents: { aadhar: 'XXXX-XXXX-9012' },
    address: '12 Lavelle Road, Bengaluru',
    capacity: 350,
    hasParking: true,
  },
  {
    id: 'v4',
    type: 'DECORATOR',
    state: 'ACTIVE',
    name: 'Petal & Paper Studio',
    contactNumber: '+91 90000 33344',
    email: 'studio@petalpaper.in',
    documents: { aadhar: 'XXXX-XXXX-3456' },
    themes: ['Floral', 'Modern Minimal', 'Vintage'],
    providesLighting: true,
  },
  {
    id: 'v5',
    type: 'PRIEST',
    state: 'ACTIVE',
    name: 'Pandit Ramesh Sharma',
    contactNumber: '+91 90000 99887',
    email: 'rsharma@vedicrites.in',
    documents: { aadhar: 'XXXX-XXXX-7890' },
    languages: ['Sanskrit', 'Hindi', 'English'],
    religion: 'Hinduism',
  },
  {
    id: 'v6',
    type: 'BAND',
    state: 'ACTIVE',
    name: 'The Mandolin Quartet',
    contactNumber: '+91 90000 22211',
    email: 'gigs@mandolinquartet.in',
    documents: { aadhar: 'XXXX-XXXX-2233' },
    instruments: ['Mandolin', 'Cello', 'Guitar', 'Vocals'],
    numberOfMembers: 4,
  },
];

export const MOCK_INVITATIONS: Invitation[] = [
  {
    id: 'inv1',
    userId: 'u1',
    title: 'Aanya & Rohan — The Wedding',
    description: 'A weekend of celebrations at The Marigold Estate.',
    date: '2026-12-12',
    location: 'Bengaluru, India',
  },
  {
    id: 'inv2',
    userId: 'u1',
    title: 'House Warming — The Mehta Residence',
    description: 'Join us for an intimate evening of celebration.',
    date: '2026-09-20',
    location: 'Mumbai, India',
  },
];

export const MOCK_STATS: Record<string, InvitationStats> = {
  inv1: {
    invitationId: 'inv1',
    totalSent: 240,
    totalYes: 168,
    totalNo: 22,
    totalMaybe: 14,
    totalNotRsvped: 36,
  },
  inv2: {
    invitationId: 'inv2',
    totalSent: 60,
    totalYes: 32,
    totalNo: 6,
    totalMaybe: 4,
    totalNotRsvped: 18,
  },
};

export const MOCK_MEDIA: Media[] = [
  {
    id: 'm1',
    name: 'event_001.jpg',
    size: 412_998,
    mimeType: 'image/jpeg',
    ownerId: 'u1',
    mediaType: 'PORTFOLIO',
    tags: ['wedding', 'ceremony'],
    fileUrl: 'https://images.unsplash.com/photo-1519741497674-611481863552?w=1200',
    thumbnailUrl: 'https://images.unsplash.com/photo-1519741497674-611481863552?w=400',
    uploadedAt: new Date().toISOString(),
  },
  {
    id: 'm2',
    name: 'event_002.jpg',
    size: 298_443,
    mimeType: 'image/jpeg',
    ownerId: 'u1',
    mediaType: 'PORTFOLIO',
    tags: ['decor'],
    fileUrl: 'https://images.unsplash.com/photo-1530023367847-a683933f4172?w=1200',
    thumbnailUrl: 'https://images.unsplash.com/photo-1530023367847-a683933f4172?w=400',
    uploadedAt: new Date().toISOString(),
  },
];
